default: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 10
  timeout: 5000
  reconnect: true

development:
  <<: *defaults
  database: oauth2_provider_development
  username: postgres
  password:

test:
  <<: *defaults
  database: oauth2_provider_test
  username: postgres
  password:
